
train:
  name: BCE_UNET7nf96_50LR001_150LRdecay0
  load_network: True
  phase_test: True
  load_epoch: 150
  shuffle: False
  input_nc: 3
  output_nc: 1
  threshold_gen: False
  n_blocks: 7
  initial_filters: 96
  dropout_value: 0
  kernel_size: 3
  strides: 2
  lr: 0.001
  decay: 0.001
  decay_epochs: 150
  batch_size: 1
  image_width: 1920
  image_height: 1280
  gen_label: None
  dataroot: /home/students/appel/Bilder/Car
  output_path: /home/temp/appel/Bilder/Results/Car/seg_gan
  model_path: /home/temp/appel/Bilder/Results/Car/seg_gan/models
  test_path: /home/students/appel/workspace/cyclegan/pytorch-CycleGAN-and-pix2pix/datasets/Car/testA
  n_epochs: 50
  steps_per_epoch: 500
  print_freq: 100
  save_freq: 1
  save_img_freq: 1